(cl:defpackage phidgets-srv
  (:use )
  (:export
   "SERVO_REFERENCE"
   "<SERVO_REFERENCE-REQUEST>"
   "SERVO_REFERENCE-REQUEST"
   "<SERVO_REFERENCE-RESPONSE>"
   "SERVO_REFERENCE-RESPONSE"
   "PID"
   "<PID-REQUEST>"
   "PID-REQUEST"
   "<PID-RESPONSE>"
   "PID-RESPONSE"
   "INTERFACE_KIT"
   "<INTERFACE_KIT-REQUEST>"
   "INTERFACE_KIT-REQUEST"
   "<INTERFACE_KIT-RESPONSE>"
   "INTERFACE_KIT-RESPONSE"
   "LIDAR_CONTROL"
   "<LIDAR_CONTROL-REQUEST>"
   "LIDAR_CONTROL-REQUEST"
   "<LIDAR_CONTROL-RESPONSE>"
   "LIDAR_CONTROL-RESPONSE"
  ))

