/* Auto-generated by genmsg_cpp for file /home/vader/catkin_ws/src/phidgets/msg/pantilt_params.msg */
#ifndef PHIDGETS_MESSAGE_PANTILT_PARAMS_H
#define PHIDGETS_MESSAGE_PANTILT_PARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace phidgets
{
template <class ContainerAllocator>
struct pantilt_params_ {
  typedef pantilt_params_<ContainerAllocator> Type;

  pantilt_params_()
  : header()
  , pan(0.0)
  , tilt(0.0)
  , timeout_sec(0.0)
  , initialise(false)
  {
  }

  pantilt_params_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pan(0.0)
  , tilt(0.0)
  , timeout_sec(0.0)
  , initialise(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _pan_type;
  double pan;

  typedef double _tilt_type;
  double tilt;

  typedef float _timeout_sec_type;
  float timeout_sec;

  typedef uint8_t _initialise_type;
  uint8_t initialise;


  typedef boost::shared_ptr< ::phidgets::pantilt_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::pantilt_params_<ContainerAllocator>  const> ConstPtr;
}; // struct pantilt_params
typedef  ::phidgets::pantilt_params_<std::allocator<void> > pantilt_params;

typedef boost::shared_ptr< ::phidgets::pantilt_params> pantilt_paramsPtr;
typedef boost::shared_ptr< ::phidgets::pantilt_params const> pantilt_paramsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phidgets::pantilt_params_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phidgets::pantilt_params_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phidgets

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phidgets::pantilt_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phidgets::pantilt_params_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phidgets::pantilt_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "09a9ad2723639c0f220e2508e17e76b8";
  }

  static const char* value(const  ::phidgets::pantilt_params_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x09a9ad2723639c0fULL;
  static const uint64_t static_value2 = 0x220e2508e17e76b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::pantilt_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phidgets/pantilt_params";
  }

  static const char* value(const  ::phidgets::pantilt_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phidgets::pantilt_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 pan\n\
float64 tilt\n\
float32 timeout_sec\n\
bool initialise\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::phidgets::pantilt_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::phidgets::pantilt_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::phidgets::pantilt_params_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phidgets::pantilt_params_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pan);
    stream.next(m.tilt);
    stream.next(m.timeout_sec);
    stream.next(m.initialise);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct pantilt_params_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::pantilt_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phidgets::pantilt_params_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pan: ";
    Printer<double>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<double>::stream(s, indent + "  ", v.tilt);
    s << indent << "timeout_sec: ";
    Printer<float>::stream(s, indent + "  ", v.timeout_sec);
    s << indent << "initialise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initialise);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_PANTILT_PARAMS_H

